# Generated by Django 2.1.4 on 2018-12-06 21:04

from django.db import migrations, models
import video_encoding.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('file', video_encoding.fields.VideoField(height_field='height', upload_to='', width_field='width')),
            ],
        ),
    ]
