# Generated by Django 2.1.4 on 2018-12-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
